import Head from "next/head";
import Hero from "../components/Hero";
import Info from "../components/Info";
import CTA from "../components/CTA";
import Services from "../components/Services";
import PkgRate from "../components/PkgRate";
import PageOptions from "../components/PageOptions";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Writing to Better Health | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <section style={{ paddingTop: "150px" }} id="about">
        <Info />
        <CTA />
      </section>

      <section style={{ paddingTop: "10px" }} id="services">
        <Services />
      </section>

      <section style={{ paddingTop: "100px" }} id="packages">
        <PkgRate />
        <PageOptions />
      </section>
    </div>
  );
}
