import Head from "next/head";
import Image from "next/image";
import HomeHero from "../components/sections/homePage/HomeHero";
import ThreeColGrid from "../components/sections/homePage/ThreeColGrid";
import PainPoints from "../components/sections/homePage/PainPoints";
import SellingPoints from "../components/sections/homePage/SellingPoints";
import DevDesignProcess from "../components/sections/homePage/DevDesignProcess";
import EmailCta from "../components/sections/homePage/EmailCta";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Writing to Better Health</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HomeHero />
        <ThreeColGrid />
        <PainPoints />
        <SellingPoints />
        <DevDesignProcess />
        <EmailCta />
      </>
    </div>
  );
}
